# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'BidmadCocos2dxSample-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BidmadCocos2dxSample-desktop

end

target 'BidmadCocos2dxSample-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BidmadCocos2dxSample-mobile
  pod 'BidmadSDK', '6.3.1'
  pod 'OpenBiddingHelper', '6.3.2'
  pod 'BidmadAdapterDynamic', '6.3.1'

end
