# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'BidmadCocos2dxSample-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BidmadCocos2dxSample-desktop

end

target 'BidmadCocos2dxSample-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BidmadCocos2dxSample-mobile
  pod 'BidmadSDK', '4.2.1.0'
  pod 'OpenBiddingHelper', '4.2.1.0'
  pod 'BidmadAdapterFNC/ForGame', '4.2.1.0'
  pod 'BidmadAdapterFC', '4.2.1.0'

end
